import Head from "next/head";

import Management from "@/app/Management";

export default function PageManagement() {
  return (
    <>
      <Head>
        <title>Salcon - Gerenciar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Management />
    </>
  );
}
